data/github_copycats.txt

Example of offending URL: https://pythonissues.com/issues/2256430

Add *://pythonissues.com/*

---

data/github_copycats.txt

Example: https://githubmate.com/repo/micronaut-projects/micronaut-cache/issues/234

Add githubmate

---

data/github_copycats.txt

- Copycat: https://tech.wayne-chu.com/archives/74468
- Original: https://stackoverflow.com/questions/67354654/symfony-5-2-render-stimulus-controller-in-twig

Add StackOverflow copycat to the blacklist

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/questions/22417007/tree-like-layouts-in-org-mode
Copycat: https://justshowmethecode.com/code-example/emacs/ewtkw/tree-like-layouts-in-org-mode

add justshowmethecode.com

---

.github/ISSUE_TEMPLATE/request-to-add-a-website-to-the-filter.md
.github/ISSUE_TEMPLATE/request-to-block-new-url-.md

Small fix to the template.
Also have a question: what is the difference between the templates?

Put 'Original' on a new line

---

README.md

Thanks for this project!  I noticed some super-minor differences between the instructions and the current uBlock Origin settings UI.  If you don't want to bother with the changes, no worries!

minor import instructions update due to UI changes

---

data/github_copycats.txt

Example: https://githubhot.com/index.php/repo/MiRO92/uYou-for-YouTube
As in Google's results:

Add githubhot.com

---

data/stackoverflow_copycats.txt

> mirrors most of GitHub/SO content, automatically and without useful additional work on the content,
* https://microeducate.tech/circular-dependency-injecting-objects-that-are-directly-depended-on-each-other/
* https://stackoverflow.com/questions/24076299/circular-dependency-injecting-objects-that-are-directly-depended-on-each-other
* https://microeducate.tech/completablefuture-usability-and-unit-test/
* https://stackoverflow.com/questions/41858894/completablefuture-usability-and-unit-test

Add microeducate

---

data/stackoverflow_copycats.txt

Evidence: https://www.ringingliberty.com/2015/12/16/how-can-i-check-if-remote_addr-ip-is-not-in-cidr-range-in-nginx/
Original: https://serverfault.com/questions/743414/how-can-i-check-if-remote-addr-ip-is-not-in-cidr-range-in-nginx
Original is serverfault.com, not stackoverflow.com, hope that's still okay

Add ringingliberty.com

---

data/github_copycats.txt

Copycat: https://lifesaver.codes/answer/mouse-interaction-with-recording-area-on-i3-52
Original: https://github.com/phw/peek/issues/52

add lifesaver.codes

---

data/stackoverflow_copycats.txt

Original source on Stack: https://stackoverflow.com/questions/69229008/how-to-change-default-size-of-android-studio-emulator-on-startup
Scraped: https://askandroidquestions.com/2021/09/17/how-to-change-default-size-of-android-studio-emulator-on-startup/
Thanks!

add stackoverflow scraper

---

data/github_copycats.txt

original URL: https://github.com/mrts/burp-suite-http-proxy-history-converter
copycat: https://pythonlang.dev/repo/mrts-burp-suite-http-proxy-history-converter/

Add pythonlang.dev

---

data/stackoverflow_copycats.txt

Evidence: https://rotadev.com/is-git-push-mirror-sufficient-for-backing-up-my-repository-dev/
Original: https://stackoverflow.com/questions/3333102/is-git-push-mirror-sufficient-for-backing-up-my-repository

Add rotadev.com

---

data/stackoverflow_copycats.txt

Evidence: https://codehunter.cc/a/git/how-to-undo-git-push-mirror
Original: https://stackoverflow.com/questions/9184438/how-to-undo-git-push-mirror

Add codehunter.cc

---

data/stackoverflow_copycats.txt

Evidence: https://readforlearn.com/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore/
Original: https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign

Add readforlearn.com

---

data/stackoverflow_copycats.txt

Evidence: https://akuum.org/questions/1274057/how-can-i-make-git--forget--about-a-file-that-was-tracked-but-is-now-in-gitignore
Original: https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign

Add akuum.org

---

data/stackoverflow_copycats.txt

Evidence: https://www.configrouter.com/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore-19675/
Original: https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign

Add configrouter.com

---

data/stackoverflow_copycats.txt

Original: https://emacs.stackexchange.com/questions/5529/how-to-right-align-some-items-in-the-modeline
Copycat: https://levitrares.com/host-https-qastack.com.br/emacs/5529/how-to-right-align-some-items-in-the-modeline (it's translated, but you can clearly seem from the URL)

add levitrares.com

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/a/66810748
Copy: https://w3coded.com/questions/37185/extending-html-lt-a-gt-tag-elements-in-react-and-typescript
Original: https://stackoverflow.com/questions/40731352/extending-html-elements-in-react-and-typescript-while-preserving-props
Copy: https://dtuto.com/questions/5499/extending-html-elements-in-react-and-typescript-while-preserving-props

Add w3coded and dtuto as SO copycats

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/questions/5647258/how-to-use-revealing-module-pattern-in-javascript
Copy:
* https://nibes.cn/blog/21417
* https://www.itbaoku.cn/post/1003279/How-to-use-Revealing-module-pattern-in-JavaScript

Add nibes.cn and itbaoku.cn to SO copycats

---

data/npm_copycats.txt

Original: https://www.npmjs.com/package/typescript-react-intl/v/0.2.2
Copy: https://codespots.com/library/item/3095

Add codespots to npm copycats

---

data/wikipedia_copycats.txt

Evidence: https://en.wikipedia.org/wiki/Lexeme
URLs:
- https://static.hlt.bme.hu/semantics/external/pages/lemma/en.wikipedia.org/wiki/Lexeme.html

data: add static.hlt.bme.hu

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/a/49209103
Copy: https://www.anycodings.com/2022/01/use-typescript-with-react-intl.html (answer 3)

Add anycodings.com to SO copycats

---

data/stackoverflow_copycats.txt

Evidence: https://serverfault.com/a/137007
URLs:
- https://ddcode.net/2019/05/07/what-is-the-difference-between-cyrus-imap-and-dovecot/

data: add ddcode.net

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/questions/62996954/how-to-refactor-a-react-component-that-is-handling-too-many-conditions-use-cas
Copy: https://w3programmers.org/questions/62996954/How-to-refactor-a-react-component-that-is-handling-too-many-conditions--use-cases

Add w3programmers.org to SO copycats

---

src/generate.py

feat: correct syntax to block url

---

data/stackoverflow_copycats.txt

Closes https://github.com/quenhus/uBlock-Origin-dev-filter/issues/220

Add Stackoverflowpoint to stackoverflow copycats 

---

data/seo_spam.txt
data/stackoverflow_copycats.txt

Evidences:
Domain | SEO   spam | SO   mirror | Evidence
-- | -- | -- | --
codesprogram.com | x |   | https://www.codesprogram.com/code-examples/html/basecamp-3-api-tag-mention
iqcode.com | x |   | https://iqcode.com/code/other/elasticsearch-docker-compose
hum-berlin.de | x |   | https://hum-berlin.de/rustic-minimalist-color-palette.html
dizzycoding.com |   | x | https://dizzycoding.com/samba-sgid-directories-and-delegation-of-privileges/
grabthiscode.com |   | x | https://grabthiscode.com/whatever/bootstrap-horizontal-form
realerlab.blogspot.com |   | x | https://realerlab.blogspot.com/2018/09/how-to-set-python-3-as-default.html
quickanswer.blog |   | x | https://www.quickanswer.blog/quick-answer-you-asked-how-do-i-run-python3-on-ubuntu/
webdesigntips.blog |   | x | …

Add mirrors

---

data/stackoverflow_copycats.txt

added bitcoden.com to stackoverflow copycats

---

data/stackoverflow_copycats.txt

Original: https://stackoverflow.com/questions/54922160/react-cloneelement-in-list-performance
Copy: https://niceans.com/answer/react-cloneelement-in-list-performance
Original: https://softwareengineering.stackexchange.com/questions/366961/is-it-antipattern-to-use-react-cloneelement-to-extend-an-element
Copy: https://itecnotes.com/software/is-it-antipattern-to-use-react-cloneelement-to-extend-an-element/
Original: https://stackoverflow.com/questions/62903691/typescript-eslint-naming-convention-how-to-mix-error-and-warn-rules
Copy: https://9to5answer.com/typescript-eslint-naming-convention-how-to-mix-error-and-warn-rules

Add niceans.com to SO

---

data/github_copycats.txt
data/old/github_copycats.txt

data: cleanup data

---

data/github_copycats.txt

Proof: https://codemonkey.link/microsoft/monaco-editor-webpack-plugin/issues/40
Original: https://github.com/microsoft/monaco-editor-webpack-plugin/issues/40

github_copycats: add https://codemonkey.link

---

data/wikipedia_copycats.txt

added russian Wiki clones - only alive ones

Update wikipedia_copycats.txt - added russian Wiki clones
